# Generated by Django 4.2.20 on 2025-12-07 03:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='Название схемы')),
                ('schema_json', models.JSONField(default=dict, verbose_name='JSON схема анкеты')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версия схемы')),
                ('generated_by_llm', models.BooleanField(default=False, verbose_name='Сгенерирована через LLM')),
                ('llm_prompt', models.TextField(blank=True, verbose_name='Промпт для LLM')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_review', 'Ожидает проверки'), ('approved', 'Утверждена'), ('archived', 'Архивная')], default='draft', max_length=20, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schemas', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
            ],
            options={
                'verbose_name': 'Схема анкеты',
                'verbose_name_plural': 'Схемы анкет',
                'ordering': ['category__name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.TextField(blank=True, verbose_name='Время работы')),
                ('is_geocoded', models.BooleanField(default=False, verbose_name='Геокодирован')),
                ('geocoded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата геокодирования')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('form_data', models.JSONField(blank=True, default=dict, verbose_name='Данные анкеты')),
                ('verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации')),
                ('moderation_status', models.CharField(choices=[('pending', 'Ожидает модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('changes_requested', 'Требуются изменения')], default='approved', max_length=20, verbose_name='Статус модерации')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('moderation_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('llm_verdict', models.JSONField(blank=True, default=dict, verbose_name='Вердикт LLM')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Точка интереса',
                'verbose_name_plural': 'Точки интереса',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POICategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=500, verbose_name='Иконка')),
                ('marker_color', models.CharField(default='#FF0000', max_length=7, verbose_name='Цвет маркера')),
                ('health_weight', models.FloatField(default=1.0, verbose_name='Вес для индекса здоровья')),
                ('health_importance', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Важность для здоровья')),
                ('display_order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория POI',
                'verbose_name_plural': 'Категории POI',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='POIRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('health_score', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Индекс здоровья')),
                ('S_infra', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Инфраструктурный рейтинг')),
                ('S_social', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Социальный рейтинг')),
                ('S_HIS', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Health Impact Score')),
                ('reviews_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество отзывов')),
                ('approved_reviews_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество подтвержденных отзывов')),
                ('average_user_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Средняя оценка пользователей')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, verbose_name='Последний расчет')),
                ('last_infra_calculation', models.DateTimeField(blank=True, null=True, verbose_name='Последний расчет S_infra')),
                ('last_social_calculation', models.DateTimeField(blank=True, null=True, verbose_name='Последний расчет S_social')),
                ('calculation_metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные расчета')),
                ('calculation_method', models.CharField(default='weighted_average', max_length=100, verbose_name='Метод расчета')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='Метрики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('poi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='maps.poi', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Рейтинг POI',
                'verbose_name_plural': 'Рейтинги POI',
                'ordering': ['-health_score'],
            },
        ),
        migrations.AddField(
            model_name='poi',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pois', to='maps.poicategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='poi',
            name='form_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='maps.formschema', verbose_name='Схема анкеты'),
        ),
        migrations.AddField(
            model_name='poi',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_pois', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='poi',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_pois', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='poi',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pois', to=settings.AUTH_USER_MODEL, verbose_name='Верифицировал'),
        ),
        migrations.AddField(
            model_name='formschema',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_schema', to='maps.poicategory', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='AreaAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('analysis_type', models.CharField(choices=[('radius', 'Анализ по радиусу'), ('city', 'Анализ по городу/округу'), ('street', 'Анализ по улице/кварталу')], max_length=20, verbose_name='Тип анализа')),
                ('area_params', models.JSONField(verbose_name='Параметры области')),
                ('active_filters', models.JSONField(default=list, verbose_name='Активные фильтры')),
                ('health_index', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Индекс здоровья')),
                ('category_stats', models.JSONField(default=dict, verbose_name='Статистика по категориям')),
                ('objects_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество объектов')),
                ('area_name', models.CharField(blank=True, max_length=500, verbose_name='Название области')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_analyses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анализ области',
                'verbose_name_plural': 'Анализы областей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['latitude', 'longitude'], name='maps_poi_latitud_a01223_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['category', 'is_active'], name='maps_poi_categor_ab2b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['is_active', 'created_at'], name='maps_poi_is_acti_1539e9_idx'),
        ),
        migrations.AddIndex(
            model_name='areaanalysis',
            index=models.Index(fields=['analysis_type', 'created_at'], name='maps_areaan_analysi_18e4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='areaanalysis',
            index=models.Index(fields=['user', 'created_at'], name='maps_areaan_user_id_3aaae0_idx'),
        ),
    ]
