# Generated by Django 4.2.20 on 2025-12-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Ожидает модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('changes_requested', 'Требуются изменения')], default='pending', max_length=20, verbose_name='Статус модерации'),
        ),
    ]
