# Generated by Django 4.2.20 on 2025-12-06 23:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные анкеты'),
        ),
        migrations.AddField(
            model_name='poi',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AddField(
            model_name='poi',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата верификации'),
        ),
        migrations.AddField(
            model_name='poi',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pois', to=settings.AUTH_USER_MODEL, verbose_name='Верифицировал'),
        ),
        migrations.AddField(
            model_name='poirating',
            name='S_HIS',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Health Impact Score'),
        ),
        migrations.AddField(
            model_name='poirating',
            name='S_infra',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Инфраструктурный рейтинг'),
        ),
        migrations.AddField(
            model_name='poirating',
            name='S_social',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Социальный рейтинг'),
        ),
        migrations.AddField(
            model_name='poirating',
            name='calculation_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные расчета'),
        ),
        migrations.AddField(
            model_name='poirating',
            name='last_infra_calculation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний расчет S_infra'),
        ),
        migrations.AddField(
            model_name='poirating',
            name='last_social_calculation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний расчет S_social'),
        ),
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='Название схемы')),
                ('schema_json', models.JSONField(default=dict, verbose_name='JSON схема анкеты')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Версия схемы')),
                ('generated_by_llm', models.BooleanField(default=False, verbose_name='Сгенерирована через LLM')),
                ('llm_prompt', models.TextField(blank=True, verbose_name='Промпт для LLM')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending_review', 'Ожидает проверки'), ('approved', 'Утверждена'), ('archived', 'Архивная')], default='draft', max_length=20, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schemas', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_schema', to='maps.poicategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Схема анкеты',
                'verbose_name_plural': 'Схемы анкет',
                'ordering': ['category__name', 'version'],
            },
        ),
        migrations.AddField(
            model_name='poi',
            name='form_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pois', to='maps.formschema', verbose_name='Схема анкеты'),
        ),
    ]
