# Generated by Django 4.2.20 on 2025-12-07 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='llm_analyzed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего LLM анализа'),
        ),
        migrations.AddField(
            model_name='poi',
            name='llm_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='LLM рейтинг (0-5)'),
        ),
        migrations.AddField(
            model_name='poi',
            name='llm_report',
            field=models.TextField(blank=True, verbose_name='LLM отчет'),
        ),
    ]
