# Generated by Django 4.2.20 on 2025-12-07 03:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Иконка')),
                ('condition', models.TextField(verbose_name='Условие получения')),
                ('bonus_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бонусные баллы')),
                ('bonus_reputation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Бонусная репутация')),
                ('rarity', models.CharField(choices=[('common', 'Обычное'), ('rare', 'Редкое'), ('epic', 'Эпическое'), ('legendary', 'Легендарное')], default='common', max_length=20, verbose_name='Редкость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['rarity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('review_type', models.CharField(choices=[('poi_review', 'Отзыв о POI'), ('incident', 'Инцидент')], max_length=20, verbose_name='Тип отзыва')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('has_media', models.BooleanField(default=False, verbose_name='Есть медиа')),
                ('is_unique', models.BooleanField(default=False, verbose_name='Уникальный')),
                ('moderation_status', models.CharField(choices=[('pending', 'Ожидает модерации'), ('approved', 'Подтвержден'), ('soft_reject', 'Неактуален'), ('spam_blocked', 'Спам')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('moderation_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1-5)')),
                ('sentiment_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Сентимент (LLM)')),
                ('extracted_facts', models.JSONField(blank=True, default=dict, verbose_name='Извлеченные факты (LLM)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('poi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='maps.poi', verbose_name='Объект POI')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reward_type', models.CharField(choices=[('coupon', 'Скидочный купон'), ('digital_merch', 'Цифровой мерч'), ('physical_merch', 'Реальный мерч'), ('privilege', 'Привилегия')], max_length=20, verbose_name='Тип награды')),
                ('points_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Стоимость в баллах')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rewards/', verbose_name='Изображение')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('stock_quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество в наличии')),
                ('sold_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Продано')),
                ('partner_name', models.CharField(blank=True, max_length=200, verbose_name='Партнер')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ['points_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Начисление'), ('debit', 'Списание')], max_length=10, verbose_name='Тип транзакции')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество баллов')),
                ('reason', models.CharField(choices=[('unique_review_approved', 'Подтвержден уникальный отзыв'), ('duplicate_review', 'Дубликат/подтверждение отзыва'), ('incident_reported', 'Зафиксирован инцидент'), ('media_attached', 'Прикреплено медиа'), ('monthly_bonus', 'Месячный бонус'), ('seasonal_activity', 'Сезонная активность'), ('achievement_bonus', 'Бонус за достижение'), ('reward_purchase', 'Покупка награды'), ('monthly_conversion', 'Конвертация в рейтинг'), ('monthly_reset', 'Месячный сброс'), ('spam_penalty', 'Штраф за спам')], max_length=50, verbose_name='Причина')),
                ('balance_after', models.IntegerField(verbose_name='Баланс после транзакции')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='gamification.review', verbose_name='Отзыв')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция наград',
                'verbose_name_plural': 'Транзакции наград',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('total_reputation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общий рейтинг')),
                ('monthly_reputation', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Месячный рейтинг')),
                ('points_balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс баллов')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Уровень')),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Опыт')),
                ('unique_reviews_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество уникальных отзывов')),
                ('spam_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество спам-отзывов')),
                ('is_banned', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('banned_until', models.DateTimeField(blank=True, null=True, verbose_name='Заблокирован до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль геймификации',
                'verbose_name_plural': 'Профили геймификации',
                'ordering': ['-total_reputation'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('action', models.CharField(choices=[('approved', 'Подтвержден'), ('soft_rejected', 'Мягкий отказ'), ('spam_blocked', 'Заблокирован как спам')], max_length=20, verbose_name='Действие')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Время обработки (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='gamification.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Лог модерации',
                'verbose_name_plural': 'Логи модерации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('used', 'Использована'), ('expired', 'Истекла')], default='active', max_length=20, verbose_name='Статус')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='gamification.reward', verbose_name='Награда')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_rewards', to='gamification.rewardtransaction', verbose_name='Транзакция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Награда пользователя',
                'verbose_name_plural': 'Награды пользователей',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'reward', 'transaction')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('progress', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Прогресс (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='gamification.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['user', 'created_at'], name='gamificatio_user_id_ccb42d_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardtransaction',
            index=models.Index(fields=['reason', 'created_at'], name='gamificatio_reason_729f47_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['latitude', 'longitude', 'created_at'], name='gamificatio_latitud_be90f1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['moderation_status', 'created_at'], name='gamificatio_moderat_5343f4_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author', 'created_at'], name='gamificatio_author__39052f_idx'),
        ),
    ]
