# Generated by Django 4.2.20 on 2025-12-06 23:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_poi_form_data_poi_verified_poi_verified_at_and_more'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='extracted_facts',
            field=models.JSONField(blank=True, default=dict, verbose_name='Извлеченные факты (LLM)'),
        ),
        migrations.AddField(
            model_name='review',
            name='poi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='maps.poi', verbose_name='Объект POI'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1-5)'),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Сентимент (LLM)'),
        ),
    ]
